[package]
name = "bluenrg"
version = "0.0.1"
authors = ["Daniel Gallagher <pdanielgallagher@gmail.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Interface to ST Micro BlueNRG Bluetooth radios"
keywords = ["spi", "bare-metal", "embedded-hal-driver"]
license = "MIT/Apache-2.0"
repository = "https://github.com/danielgallagher0/bluenrg"

[dependencies]
nb = "0.1.1"
ble = { git = "https://github.com/danielgallagher0/ble-rs" }

[dependencies.embedded-hal]
version = "0.1.0"
features = ["unproven"]
